-- Statistics infrastructure.
--
-- The statistics dashboard relies on two data sources:
--
--   1. `istoric_raspunsuri` — one row per answer attempt. Extended here with
--      `examen_id` and `mod` so we can partition queries by exam/mode and
--      compute a per-question "last attempt" without scanning every row.
--
--   2. `sesiuni_simulare` — a new table that records finished simulation
--      sessions (start/finish timestamps, duration, score, pass/fail).
--      Practice sessions are intentionally excluded so the evolution chart
--      only reflects exam-realistic attempts.
--
-- Both tables run with row-level security so users can only see/insert
-- their own rows.

-- 1. Extend istoric_raspunsuri ---------------------------------------------
ALTER TABLE public.istoric_raspunsuri
  ADD COLUMN IF NOT EXISTS examen_id integer
    REFERENCES public.examene(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS mod text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'istoric_raspunsuri_mod_check'
      AND conrelid = 'public.istoric_raspunsuri'::regclass
  ) THEN
    ALTER TABLE public.istoric_raspunsuri
      ADD CONSTRAINT istoric_raspunsuri_mod_check
      CHECK (mod IS NULL OR mod IN ('simulare', 'practica'));
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS istoric_raspunsuri_user_exam_idx
  ON public.istoric_raspunsuri (user_id, examen_id, data_raspuns DESC);

CREATE INDEX IF NOT EXISTS istoric_raspunsuri_user_question_idx
  ON public.istoric_raspunsuri (user_id, intrebare_id, data_raspuns DESC);

-- Enable RLS (already enabled per the project, but defensive) and add a
-- single policy that mirrors the pattern used for bookmarks / status_invatare.
ALTER TABLE public.istoric_raspunsuri ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage their own answer history"
  ON public.istoric_raspunsuri;
CREATE POLICY "Users can manage their own answer history"
  ON public.istoric_raspunsuri
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 2. Create sesiuni_simulare ----------------------------------------------
CREATE TABLE IF NOT EXISTS public.sesiuni_simulare (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  examen_id integer NOT NULL REFERENCES public.examene(id) ON DELETE CASCADE,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz NOT NULL DEFAULT now(),
  durata_secunde integer NOT NULL DEFAULT 0,
  raspunsuri_corecte integer NOT NULL DEFAULT 0,
  total_intrebari integer NOT NULL DEFAULT 0,
  scor_procent numeric(5, 2) NOT NULL DEFAULT 0,
  finalizat boolean NOT NULL DEFAULT true,
  timed_out boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS sesiuni_simulare_user_exam_idx
  ON public.sesiuni_simulare (user_id, examen_id, finished_at DESC);

ALTER TABLE public.sesiuni_simulare ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage their own simulation sessions"
  ON public.sesiuni_simulare;
CREATE POLICY "Users can manage their own simulation sessions"
  ON public.sesiuni_simulare
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
