-- Practice session durations feed the global “Timp dedicat” stat while
-- `sesiuni_simulare` continues to anchor evolution-chart-only metrics.

CREATE TABLE IF NOT EXISTS public.sesiuni_practica (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  examen_id integer NOT NULL REFERENCES public.examene(id) ON DELETE CASCADE,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz NOT NULL DEFAULT now(),
  durata_secunde integer NOT NULL DEFAULT 0,
  raspunsuri_corecte integer NOT NULL DEFAULT 0,
  total_intrebari integer NOT NULL DEFAULT 0,
  finalizat boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS sesiuni_practica_user_exam_idx
  ON public.sesiuni_practica (user_id, examen_id, finished_at DESC);

ALTER TABLE public.sesiuni_practica ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage their own practice sessions"
  ON public.sesiuni_practica;
CREATE POLICY "Users can manage their own practice sessions"
  ON public.sesiuni_practica
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
